name: example
description: examples of easy_orm
publish_to: none

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  easy_orm_postgres:
    path: ../easy_orm_postgres
  postgres: ^2.5.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  test: ^1.18.2
  tuple: ^2.0.0
