name: example
description: examples of postgrest_typed
publish_to: none

environment:
  sdk: '>=2.17.0-0 <3.0.0'

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  easy_orm_engine:
    path: ../easy_orm_engine
  postgres: ^2.5.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^2.1.1
  json_serializable: ^6.4.1
  test: ^1.18.2
