#a list of views to upload from the
customer_customer_demo:
customer_demographics:

#the columns specified include the table name & column name indended by 2 chars
# on the next line
employees:
  photo_path