version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '5433:5433'
    command:
      -p 5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
    volumes:
      - easy_orm_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  easy_orm_data:
