// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'EmployeeFreezed.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'EmployeeFreezed.g.dart';

@freezed
class EmployeeF with _$EmployeeF {
  const factory EmployeeF({
    required int employee_id,
    required String title_of_courtesy,
  }) = _EmployeeF;

  factory EmployeeF.fromJson(Map<String, Object?> json) => //
      _$EmployeeFFromJson(json);
}
