name: easy_orm_cli
description: The CLI used to generate ORM code for easy_orm.
version: 0.3.0
executables:
  easy_orm_cli:
repository: https://github.com/atreeon/easy_orm/

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  super_string: ^1.0.3
  colorize: ^3.0.0
  easy_orm_postgres:
    path: ../easy_orm_postgres
  templater_atreeon: ^1.0.0
  basic_utils: ^5.3.0
  postgres: ^2.5.0
  collection: ^1.16.0
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.21.6

