name: easy_orm_cli
description: The CLI used to generate ORM code for easy_orm.
version: 0.4.0
executables:
  easy_orm_cli:
repository: https://github.com/atreeon/easy_orm/

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  easy_orm_postgres: ^0.4.0
  super_string: ^1.0.3
  colorize: ^3.0.0
  templater_atreeon: ^1.0.0
  basic_utils: ^5.3.0
  postgres: ^2.5.0
  collection: ^1.16.0
  tuple: ^2.0.0
  args: ^2.3.1
  path: ^1.8.2
  yaml: ^3.1.1
  dartx: ^1.1.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  test: ^1.21.6

dependency_overrides:
  easy_orm_postgres:
    path: ../easy_orm_postgres
