name: postgrest_cli
description: The CLI used to generate ORM code for easy_orm.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  super_string: ^1.0.3
  colorize: ^3.0.0
  easy_orm_engine:
    path: ../easy_orm_engine
  templater_atreeon:
    git: https://github.com/atreeon/templater_atreeon.git
  basic_utils: ^5.3.0
  postgres: ^2.5.0
  collection: ^1.16.0
  tuple: ^2.0.0

dev_dependencies:
  test: ^1.21.6

